package com.Medical.dao.enums;

public enum MedicalCategories {
    INTERNAL_MEDICINE,
    PEDIATRICS,
    SURGERY,
    OBSTETRICS_AND_GYNECOLOGY,
    CARDIOLOGY,
    DERMATOLOGY,
    NEUROLOGY,
    PSYCHIATRY,
    ONCOLOGY,
    RADIOLOGY,
    ANESTHESIOLOGY,
    EMERGENCY_MEDICINE,
    PATHOLOGY,
    ALLERGY_AND_IMMUNOLOGY,
    RHEUMATOLOGY,
    GERIATRICS,
    ENDOCRINOLOGY,
    HEMATOLOGY,
    NEPHROLOGY,
    UROLOGY
}
